### ISSUE TITLE
sort and fields, and other options

### ISSUE THREAD

**Issue by raisch** [legalthings/mongodb-rest#31]
After a quick test of the various query options, I find

```
?query={"city":"foo"}&fields={"name":1}     crashes server
?query={"city":"foo"}&hint={"name":1}       crashes server
?query={"city":"foo"}&sort={"name":-1}      ignored
?query={"city":"foo"}&explain=1             crashes server
```

The first three can be fixed by changing line 31 of rest.js from

```
options[o] = req.query[o];
```

to

```
options[o] = JSON.parse(req.query[o]);
```

But it should be noted that the server code for this project is **VERY** brittle, lacking any sort of defensive programming or error-handling.

**Comment by Minstel** [comment]
Confirmed for `hint` operation
