### ISSUE TITLE
Cannot call method 'collection' of null

### ISSUE THREAD

**Issue by dileephell** [legalthings/mongodb-rest#36]
var Db = require('mongodb').Db;
var Server = require('mongodb').Server;
new Db('db-login', new Server('localhost', '27017'));
var db = new Db('db-login', new Server('localhost', '27017', { auto_reconnect: true },{safe:false}));

db.open(function (err, db) {
    if (err) { console.log(err + ' db open error') }
    db.authenticate('jones', 'jones', function (err, result) {
        if (err) { console.log(err + ' auth error'); }
        else{ console.log('Authenticated..'); }
    });
});

exports.getlogin=function getlogin(uid,pwd,callback){
Db.connect('mongodb://admin:markingof@localhost:27017/db-login', function (err, db) {
    db.collection('maccount_logins', function(err, collection) {

```
collection.find({"user.userid":uid,"user.pwd":pwd,"user.status":"true"},{"acc_type":"","acc_prefix":"","db_name":"","user.role":"","_id":0}).toArray(function(err, items) {
    if(err){console.log(err+'i am stuck');}
    else{

            callback("",items);
    }



 });
```

   });
    });
};

**Comment by Minstel** [comment]
@dileephell Issue is not clear.
