### ISSUE TITLE
Add authentication?

### ISSUE THREAD

**Issue by superbobry** [legalthings/mongodb-rest#4]
Hello, any plans to plug in basic or digest auth support?

**Comment by Minstel** [comment]
Implemented in https://github.com/legalthings/mongodb-rest/pull/45

**Comment by KenEucker** [comment]
Thanks for this update @ashleydavis. I no longer work on the project I originally needed this for, but am excited to see this become a more usable solution. I look forward to testing out my idea with this feature in the near future!
